---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: front:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: front-env
      terminationGracePeriodSeconds: 180